import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import localFont from 'next/font/local'
import "./globals.css";

const trap = localFont({
  src: [
    {
      path: './fonts/Trap-Light.otf',
      weight: '300',
      style: 'normal',
    },
    {
      path: './fonts/Trap-Regular.otf',
      weight: '400',
      style: 'normal',
    },
    {
      path: './fonts/Trap-Medium.otf',
      weight: '500',
      style: 'normal',
    },
    {
      path: './fonts/Trap-SemiBold.otf',
      weight: '600',
      style: 'normal',
    },
    {
      path: './fonts/Trap-Bold.otf',
      weight: '700',
      style: 'normal',
    },
    {
      path: './fonts/Trap-ExtraBold.otf',
      weight: '800',
      style: 'normal',
    },
    {
      path: './fonts/Trap-Black.otf',
      weight: '900',
      style: 'normal',
    },
  ],
  variable: '--font-trap'
})

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"]
});

export const metadata: Metadata = {
  title: "Mohoncon Builders",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${trap.variable} ${poppins.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
